# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'v1.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QHeaderView, QLabel, QListView, QMainWindow,
    QPlainTextEdit, QProgressBar, QPushButton, QSizePolicy,
    QTabWidget, QTableView, QToolButton, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(661, 400)
        MainWindow.setMinimumSize(QSize(661, 400))
        MainWindow.setMaximumSize(QSize(661, 400))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(660, 400))
        self.centralwidget.setMaximumSize(QSize(660, 400))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 661, 401))
        self.tabWidget.setMinimumSize(QSize(661, 401))
        self.tabWidget.setMaximumSize(QSize(661, 440))
        self.tabWidget.setElideMode(Qt.TextElideMode.ElideMiddle)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.TreeMode = QWidget()
        self.TreeMode.setObjectName(u"TreeMode")
        self.path_Tree = QPlainTextEdit(self.TreeMode)
        self.path_Tree.setObjectName(u"path_Tree")
        self.path_Tree.setGeometry(QRect(10, 3, 641, 61))
        font = QFont()
        font.setPointSize(15)
        self.path_Tree.setFont(font)
        self.SelectionButton_Tree = QPushButton(self.TreeMode)
        self.SelectionButton_Tree.setObjectName(u"SelectionButton_Tree")
        self.SelectionButton_Tree.setGeometry(QRect(480, 80, 161, 31))
        self.SelectionButton_Tree.setAutoDefault(False)
        self.SelectionButton_Tree.setFlat(True)
        self.progressBar_Tree = QProgressBar(self.TreeMode)
        self.progressBar_Tree.setObjectName(u"progressBar_Tree")
        self.progressBar_Tree.setGeometry(QRect(170, 80, 311, 31))
        self.progressBar_Tree.setValue(24)
        self.loadBatton_Tree = QPushButton(self.TreeMode)
        self.loadBatton_Tree.setObjectName(u"loadBatton_Tree")
        self.loadBatton_Tree.setGeometry(QRect(60, 80, 101, 31))
        self.loadBatton_Tree.setFlat(True)
        self.resetButton_Tree = QPushButton(self.TreeMode)
        self.resetButton_Tree.setObjectName(u"resetButton_Tree")
        self.resetButton_Tree.setGeometry(QRect(10, 80, 41, 31))
        self.resetButton_Tree.setAutoFillBackground(False)
        self.resetButton_Tree.setFlat(True)
        self.label_Reset_Tree = QLabel(self.TreeMode)
        self.label_Reset_Tree.setObjectName(u"label_Reset_Tree")
        self.label_Reset_Tree.setGeometry(QRect(15, 65, 31, 16))
        self.Stages_List_View_Tree = QListView(self.TreeMode)
        self.Stages_List_View_Tree.setObjectName(u"Stages_List_View_Tree")
        self.Stages_List_View_Tree.setGeometry(QRect(10, 200, 401, 161))
        self.Stages_List_View_Tree.setAutoFillBackground(True)
        self.plainTextIP_Tree = QPlainTextEdit(self.TreeMode)
        self.plainTextIP_Tree.setObjectName(u"plainTextIP_Tree")
        self.plainTextIP_Tree.setGeometry(QRect(450, 200, 201, 31))
        self.plainTextIP_Tree.setAutoFillBackground(True)
        self.plainTextIP_Tree.setReadOnly(False)
        self.label_IP_Tree = QLabel(self.TreeMode)
        self.label_IP_Tree.setObjectName(u"label_IP_Tree")
        self.label_IP_Tree.setGeometry(QRect(420, 200, 21, 31))
        font1 = QFont()
        font1.setPointSize(12)
        self.label_IP_Tree.setFont(font1)
        self.label_ID_Auto_2 = QLabel(self.TreeMode)
        self.label_ID_Auto_2.setObjectName(u"label_ID_Auto_2")
        self.label_ID_Auto_2.setGeometry(QRect(420, 330, 49, 16))
        self.label_ID_Auto_2.setFont(font1)
        self.plainText_Port_Tree = QPlainTextEdit(self.TreeMode)
        self.plainText_Port_Tree.setObjectName(u"plainText_Port_Tree")
        self.plainText_Port_Tree.setGeometry(QRect(450, 260, 201, 31))
        self.plainText_Port_Tree.setAutoFillBackground(True)
        self.plainText_Port_Tree.setReadOnly(False)
        self.plainText_ID_Tree = QPlainTextEdit(self.TreeMode)
        self.plainText_ID_Tree.setObjectName(u"plainText_ID_Tree")
        self.plainText_ID_Tree.setGeometry(QRect(450, 320, 201, 31))
        self.plainText_ID_Tree.setAutoFillBackground(True)
        self.plainText_ID_Tree.setReadOnly(False)
        self.label_Port_Auto_2 = QLabel(self.TreeMode)
        self.label_Port_Auto_2.setObjectName(u"label_Port_Auto_2")
        self.label_Port_Auto_2.setGeometry(QRect(420, 270, 41, 16))
        self.label_Port_Auto_2.setFont(font1)
        self.comboBox_Level_1_Name_Tree = QComboBox(self.TreeMode)
        self.comboBox_Level_1_Name_Tree.addItem("")
        self.comboBox_Level_1_Name_Tree.addItem("")
        self.comboBox_Level_1_Name_Tree.addItem("")
        self.comboBox_Level_1_Name_Tree.addItem("")
        self.comboBox_Level_1_Name_Tree.addItem("")
        self.comboBox_Level_1_Name_Tree.setObjectName(u"comboBox_Level_1_Name_Tree")
        self.comboBox_Level_1_Name_Tree.setGeometry(QRect(10, 130, 89, 26))
        self.comboBox_Level_1_ID_Tree = QComboBox(self.TreeMode)
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.addItem("")
        self.comboBox_Level_1_ID_Tree.setObjectName(u"comboBox_Level_1_ID_Tree")
        self.comboBox_Level_1_ID_Tree.setGeometry(QRect(140, 130, 51, 26))
        self.comboBox_Level_2_Name_Tree = QComboBox(self.TreeMode)
        self.comboBox_Level_2_Name_Tree.addItem("")
        self.comboBox_Level_2_Name_Tree.addItem("")
        self.comboBox_Level_2_Name_Tree.addItem("")
        self.comboBox_Level_2_Name_Tree.addItem("")
        self.comboBox_Level_2_Name_Tree.addItem("")
        self.comboBox_Level_2_Name_Tree.setObjectName(u"comboBox_Level_2_Name_Tree")
        self.comboBox_Level_2_Name_Tree.setGeometry(QRect(230, 130, 89, 26))
        self.comboBox_Level_3_Name_Tree = QComboBox(self.TreeMode)
        self.comboBox_Level_3_Name_Tree.addItem("")
        self.comboBox_Level_3_Name_Tree.addItem("")
        self.comboBox_Level_3_Name_Tree.addItem("")
        self.comboBox_Level_3_Name_Tree.addItem("")
        self.comboBox_Level_3_Name_Tree.addItem("")
        self.comboBox_Level_3_Name_Tree.setObjectName(u"comboBox_Level_3_Name_Tree")
        self.comboBox_Level_3_Name_Tree.setGeometry(QRect(450, 130, 89, 26))
        self.label_pointer_Tree_1 = QLabel(self.TreeMode)
        self.label_pointer_Tree_1.setObjectName(u"label_pointer_Tree_1")
        self.label_pointer_Tree_1.setGeometry(QRect(100, 130, 41, 20))
        font2 = QFont()
        font2.setPointSize(30)
        font2.setBold(False)
        font2.setItalic(True)
        font2.setUnderline(False)
        font2.setStrikeOut(False)
        self.label_pointer_Tree_1.setFont(font2)
        self.label_pointer_Tree_2 = QLabel(self.TreeMode)
        self.label_pointer_Tree_2.setObjectName(u"label_pointer_Tree_2")
        self.label_pointer_Tree_2.setGeometry(QRect(190, 130, 41, 20))
        self.label_pointer_Tree_2.setFont(font2)
        self.label_pointer_Tree_3 = QLabel(self.TreeMode)
        self.label_pointer_Tree_3.setObjectName(u"label_pointer_Tree_3")
        self.label_pointer_Tree_3.setGeometry(QRect(320, 130, 41, 20))
        self.label_pointer_Tree_3.setFont(font2)
        self.label_pointer_Tree_4 = QLabel(self.TreeMode)
        self.label_pointer_Tree_4.setObjectName(u"label_pointer_Tree_4")
        self.label_pointer_Tree_4.setGeometry(QRect(410, 130, 41, 20))
        self.label_pointer_Tree_4.setFont(font2)
        self.label_pointer_Tree_5 = QLabel(self.TreeMode)
        self.label_pointer_Tree_5.setObjectName(u"label_pointer_Tree_5")
        self.label_pointer_Tree_5.setGeometry(QRect(540, 130, 41, 20))
        self.label_pointer_Tree_5.setFont(font2)
        self.comboBox_Level_2_ID_Tree = QComboBox(self.TreeMode)
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.addItem("")
        self.comboBox_Level_2_ID_Tree.setObjectName(u"comboBox_Level_2_ID_Tree")
        self.comboBox_Level_2_ID_Tree.setGeometry(QRect(360, 130, 51, 26))
        self.comboBox_Level_3_ID_Tree = QComboBox(self.TreeMode)
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.addItem("")
        self.comboBox_Level_3_ID_Tree.setObjectName(u"comboBox_Level_3_ID_Tree")
        self.comboBox_Level_3_ID_Tree.setGeometry(QRect(580, 130, 51, 26))
        self.tabWidget.addTab(self.TreeMode, "")
        self.AutoMode = QWidget()
        self.AutoMode.setObjectName(u"AutoMode")
        self.SelectionButton_Auto = QPushButton(self.AutoMode)
        self.SelectionButton_Auto.setObjectName(u"SelectionButton_Auto")
        self.SelectionButton_Auto.setGeometry(QRect(480, 80, 161, 31))
        self.SelectionButton_Auto.setAutoDefault(False)
        self.SelectionButton_Auto.setFlat(True)
        self.loadBatton_Auto = QPushButton(self.AutoMode)
        self.loadBatton_Auto.setObjectName(u"loadBatton_Auto")
        self.loadBatton_Auto.setGeometry(QRect(60, 80, 101, 31))
        self.loadBatton_Auto.setFlat(True)
        self.plainText_Name_Auto = QPlainTextEdit(self.AutoMode)
        self.plainText_Name_Auto.setObjectName(u"plainText_Name_Auto")
        self.plainText_Name_Auto.setGeometry(QRect(490, 150, 161, 31))
        self.plainText_Name_Auto.setAcceptDrops(False)
        self.plainText_Name_Auto.setAutoFillBackground(True)
        self.plainText_Name_Auto.setReadOnly(True)
        self.plainText_Type_Auto = QPlainTextEdit(self.AutoMode)
        self.plainText_Type_Auto.setObjectName(u"plainText_Type_Auto")
        self.plainText_Type_Auto.setGeometry(QRect(490, 190, 161, 31))
        self.plainText_Type_Auto.setAutoFillBackground(True)
        self.plainText_Type_Auto.setReadOnly(True)
        self.plainText_ID_Auto = QPlainTextEdit(self.AutoMode)
        self.plainText_ID_Auto.setObjectName(u"plainText_ID_Auto")
        self.plainText_ID_Auto.setGeometry(QRect(490, 230, 161, 31))
        self.plainText_ID_Auto.setAutoFillBackground(True)
        self.plainText_ID_Auto.setReadOnly(False)
        self.plainText_Port_Auto = QPlainTextEdit(self.AutoMode)
        self.plainText_Port_Auto.setObjectName(u"plainText_Port_Auto")
        self.plainText_Port_Auto.setGeometry(QRect(490, 270, 161, 31))
        self.plainText_Port_Auto.setAutoFillBackground(True)
        self.plainText_Port_Auto.setReadOnly(False)
        self.plainText_IP_Auto = QPlainTextEdit(self.AutoMode)
        self.plainText_IP_Auto.setObjectName(u"plainText_IP_Auto")
        self.plainText_IP_Auto.setGeometry(QRect(490, 310, 161, 31))
        self.plainText_IP_Auto.setAutoFillBackground(True)
        self.plainText_IP_Auto.setReadOnly(False)
        self.path_Auto = QPlainTextEdit(self.AutoMode)
        self.path_Auto.setObjectName(u"path_Auto")
        self.path_Auto.setGeometry(QRect(10, 3, 641, 61))
        self.path_Auto.setFont(font)
        self.progressBar_Auto = QProgressBar(self.AutoMode)
        self.progressBar_Auto.setObjectName(u"progressBar_Auto")
        self.progressBar_Auto.setGeometry(QRect(170, 80, 311, 31))
        self.progressBar_Auto.setValue(24)
        self.label_Name_Auto = QLabel(self.AutoMode)
        self.label_Name_Auto.setObjectName(u"label_Name_Auto")
        self.label_Name_Auto.setGeometry(QRect(440, 160, 49, 16))
        self.label_Name_Auto.setFont(font1)
        self.label_Specifier_Auto = QLabel(self.AutoMode)
        self.label_Specifier_Auto.setObjectName(u"label_Specifier_Auto")
        self.label_Specifier_Auto.setGeometry(QRect(430, 200, 61, 16))
        self.label_Specifier_Auto.setFont(font1)
        self.label_ID_Auto = QLabel(self.AutoMode)
        self.label_ID_Auto.setObjectName(u"label_ID_Auto")
        self.label_ID_Auto.setGeometry(QRect(440, 240, 49, 16))
        self.label_ID_Auto.setFont(font1)
        self.label_Port_Auto = QLabel(self.AutoMode)
        self.label_Port_Auto.setObjectName(u"label_Port_Auto")
        self.label_Port_Auto.setGeometry(QRect(440, 280, 49, 16))
        self.label_Port_Auto.setFont(font1)
        self.label_IP_Auto = QLabel(self.AutoMode)
        self.label_IP_Auto.setObjectName(u"label_IP_Auto")
        self.label_IP_Auto.setGeometry(QRect(440, 320, 49, 16))
        self.label_IP_Auto.setFont(font1)
        self.Stages_List_View_Auto = QListView(self.AutoMode)
        self.Stages_List_View_Auto.setObjectName(u"Stages_List_View_Auto")
        self.Stages_List_View_Auto.setGeometry(QRect(10, 120, 411, 241))
        self.Stages_List_View_Auto.setAutoFillBackground(True)
        self.resetButton_Auto = QPushButton(self.AutoMode)
        self.resetButton_Auto.setObjectName(u"resetButton_Auto")
        self.resetButton_Auto.setGeometry(QRect(10, 80, 41, 31))
        self.resetButton_Auto.setAutoFillBackground(False)
        self.resetButton_Auto.setFlat(True)
        self.label_Reset_Auto = QLabel(self.AutoMode)
        self.label_Reset_Auto.setObjectName(u"label_Reset_Auto")
        self.label_Reset_Auto.setGeometry(QRect(15, 65, 31, 16))
        self.tabWidget.addTab(self.AutoMode, "")
        self.ManualMode = QWidget()
        self.ManualMode.setObjectName(u"ManualMode")
        self.SelectionButton_Manual = QPushButton(self.ManualMode)
        self.SelectionButton_Manual.setObjectName(u"SelectionButton_Manual")
        self.SelectionButton_Manual.setGeometry(QRect(480, 80, 161, 31))
        self.SelectionButton_Manual.setAutoDefault(False)
        self.SelectionButton_Manual.setFlat(True)
        self.loadBatton_Manual = QPushButton(self.ManualMode)
        self.loadBatton_Manual.setObjectName(u"loadBatton_Manual")
        self.loadBatton_Manual.setGeometry(QRect(60, 80, 101, 31))
        self.loadBatton_Manual.setFlat(True)
        self.path_Manual = QPlainTextEdit(self.ManualMode)
        self.path_Manual.setObjectName(u"path_Manual")
        self.path_Manual.setGeometry(QRect(10, 3, 641, 61))
        self.path_Manual.setFont(font)
        self.progress_Bar_Manual = QProgressBar(self.ManualMode)
        self.progress_Bar_Manual.setObjectName(u"progress_Bar_Manual")
        self.progress_Bar_Manual.setGeometry(QRect(170, 80, 311, 31))
        self.progress_Bar_Manual.setValue(24)
        self.plainTextPort_Manual = QPlainTextEdit(self.ManualMode)
        self.plainTextPort_Manual.setObjectName(u"plainTextPort_Manual")
        self.plainTextPort_Manual.setGeometry(QRect(480, 200, 161, 31))
        self.plainTextPort_Manual.setAutoFillBackground(True)
        self.plainTextPort_Manual.setReadOnly(False)
        self.plainTextIP_Manual = QPlainTextEdit(self.ManualMode)
        self.plainTextIP_Manual.setObjectName(u"plainTextIP_Manual")
        self.plainTextIP_Manual.setGeometry(QRect(480, 290, 161, 31))
        self.plainTextIP_Manual.setAutoFillBackground(True)
        self.plainTextIP_Manual.setReadOnly(False)
        self.plainTextID_Manual = QPlainTextEdit(self.ManualMode)
        self.plainTextID_Manual.setObjectName(u"plainTextID_Manual")
        self.plainTextID_Manual.setGeometry(QRect(480, 140, 161, 31))
        self.plainTextID_Manual.setAutoFillBackground(True)
        self.plainTextID_Manual.setReadOnly(False)
        self.label_ID_Manual = QLabel(self.ManualMode)
        self.label_ID_Manual.setObjectName(u"label_ID_Manual")
        self.label_ID_Manual.setGeometry(QRect(450, 150, 49, 16))
        self.label_ID_Manual.setFont(font1)
        self.label_Port_Manual = QLabel(self.ManualMode)
        self.label_Port_Manual.setObjectName(u"label_Port_Manual")
        self.label_Port_Manual.setGeometry(QRect(440, 210, 49, 16))
        self.label_Port_Manual.setFont(font1)
        self.label_IP_Manual = QLabel(self.ManualMode)
        self.label_IP_Manual.setObjectName(u"label_IP_Manual")
        self.label_IP_Manual.setGeometry(QRect(550, 240, 16, 16))
        self.label_IP_Manual.setFont(font1)
        self.checkBox_Yes_IP = QCheckBox(self.ManualMode)
        self.checkBox_Yes_IP.setObjectName(u"checkBox_Yes_IP")
        self.checkBox_Yes_IP.setGeometry(QRect(480, 260, 51, 24))
        self.checkBox_Yes_IP.setAutoFillBackground(False)
        self.checkBox_NO_IP = QCheckBox(self.ManualMode)
        self.checkBox_NO_IP.setObjectName(u"checkBox_NO_IP")
        self.checkBox_NO_IP.setGeometry(QRect(590, 260, 51, 24))
        self.checkBox_NO_IP.setAutoFillBackground(False)
        self.checkBox_Safety_Mode_Manual = QCheckBox(self.ManualMode)
        self.checkBox_Safety_Mode_Manual.setObjectName(u"checkBox_Safety_Mode_Manual")
        self.checkBox_Safety_Mode_Manual.setGeometry(QRect(480, 330, 161, 21))
        self.checkBox_Safety_Mode_Manual.setFont(font1)
        self.checkBox_Safety_Mode_Manual.setAutoFillBackground(False)
        self.checkBox_Safety_Mode_Manual.setChecked(True)
        self.checkBox_Safety_Mode_Manual.setAutoRepeat(False)
        self.checkBox_Safety_Mode_Manual.setAutoExclusive(False)
        self.checkBox_Safety_Mode_Manual.setTristate(False)
        self.Stages_List_View_Manual = QListView(self.ManualMode)
        self.Stages_List_View_Manual.setObjectName(u"Stages_List_View_Manual")
        self.Stages_List_View_Manual.setGeometry(QRect(10, 120, 411, 241))
        self.Stages_List_View_Manual.setAutoFillBackground(True)
        self.resetButton_Manual = QPushButton(self.ManualMode)
        self.resetButton_Manual.setObjectName(u"resetButton_Manual")
        self.resetButton_Manual.setGeometry(QRect(10, 80, 41, 31))
        self.resetButton_Manual.setAutoFillBackground(False)
        self.resetButton_Manual.setFlat(True)
        self.label_Reset_Manual = QLabel(self.ManualMode)
        self.label_Reset_Manual.setObjectName(u"label_Reset_Manual")
        self.label_Reset_Manual.setGeometry(QRect(15, 65, 31, 16))
        self.tabWidget.addTab(self.ManualMode, "")
        self.Config = QWidget()
        self.Config.setObjectName(u"Config")
        self.Configuration_List_Config = QTableView(self.Config)
        self.Configuration_List_Config.setObjectName(u"Configuration_List_Config")
        self.Configuration_List_Config.setGeometry(QRect(10, 10, 361, 351))
        self.Configuration_List_Config.setAutoFillBackground(True)
        self.Configuration_List_Config.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.Configuration_List_Config.setFrameShadow(QFrame.Shadow.Sunken)
        self.Configuration_List_Config.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.plainText_Port_Config = QPlainTextEdit(self.Config)
        self.plainText_Port_Config.setObjectName(u"plainText_Port_Config")
        self.plainText_Port_Config.setGeometry(QRect(480, 190, 161, 31))
        self.plainText_Port_Config.setAutoFillBackground(True)
        self.plainText_Port_Config.setReadOnly(False)
        self.label_Name_Config = QLabel(self.Config)
        self.label_Name_Config.setObjectName(u"label_Name_Config")
        self.label_Name_Config.setGeometry(QRect(430, 80, 49, 16))
        self.label_Name_Config.setFont(font1)
        self.plainText_IP_Config = QPlainTextEdit(self.Config)
        self.plainText_IP_Config.setObjectName(u"plainText_IP_Config")
        self.plainText_IP_Config.setGeometry(QRect(480, 330, 161, 31))
        self.plainText_IP_Config.setAutoFillBackground(True)
        self.plainText_IP_Config.setReadOnly(False)
        self.plainText_Specifier_Config = QPlainTextEdit(self.Config)
        self.plainText_Specifier_Config.setObjectName(u"plainText_Specifier_Config")
        self.plainText_Specifier_Config.setGeometry(QRect(480, 110, 161, 31))
        self.plainText_Specifier_Config.setAutoFillBackground(True)
        self.plainText_Specifier_Config.setReadOnly(False)
        self.label_Specifier_Config = QLabel(self.Config)
        self.label_Specifier_Config.setObjectName(u"label_Specifier_Config")
        self.label_Specifier_Config.setGeometry(QRect(420, 110, 61, 31))
        self.label_Specifier_Config.setFont(font1)
        self.plainText_ID_Config = QPlainTextEdit(self.Config)
        self.plainText_ID_Config.setObjectName(u"plainText_ID_Config")
        self.plainText_ID_Config.setGeometry(QRect(480, 150, 161, 31))
        self.plainText_ID_Config.setAutoFillBackground(True)
        self.plainText_ID_Config.setReadOnly(False)
        self.plainText_Name_Config = QPlainTextEdit(self.Config)
        self.plainText_Name_Config.setObjectName(u"plainText_Name_Config")
        self.plainText_Name_Config.setGeometry(QRect(480, 70, 161, 31))
        self.plainText_Name_Config.setAcceptDrops(False)
        self.plainText_Name_Config.setAutoFillBackground(True)
        self.plainText_Name_Config.setReadOnly(False)
        self.label_ID_Config = QLabel(self.Config)
        self.label_ID_Config.setObjectName(u"label_ID_Config")
        self.label_ID_Config.setGeometry(QRect(430, 160, 49, 16))
        self.label_ID_Config.setFont(font1)
        self.label_Port_Config = QLabel(self.Config)
        self.label_Port_Config.setObjectName(u"label_Port_Config")
        self.label_Port_Config.setGeometry(QRect(430, 200, 49, 16))
        self.label_Port_Config.setFont(font1)
        self.checkBox_NO_IP_2 = QCheckBox(self.Config)
        self.checkBox_NO_IP_2.setObjectName(u"checkBox_NO_IP_2")
        self.checkBox_NO_IP_2.setGeometry(QRect(580, 300, 51, 24))
        self.checkBox_NO_IP_2.setAutoFillBackground(False)
        self.label_IP_Config = QLabel(self.Config)
        self.label_IP_Config.setObjectName(u"label_IP_Config")
        self.label_IP_Config.setGeometry(QRect(550, 290, 16, 16))
        self.label_IP_Config.setFont(font1)
        self.checkBox_Yes_IP_2 = QCheckBox(self.Config)
        self.checkBox_Yes_IP_2.setObjectName(u"checkBox_Yes_IP_2")
        self.checkBox_Yes_IP_2.setGeometry(QRect(480, 300, 51, 24))
        self.checkBox_Yes_IP_2.setAutoFillBackground(False)
        self.plainText_Specifier_Optional_Config = QPlainTextEdit(self.Config)
        self.plainText_Specifier_Optional_Config.setObjectName(u"plainText_Specifier_Optional_Config")
        self.plainText_Specifier_Optional_Config.setGeometry(QRect(480, 250, 161, 31))
        self.plainText_Specifier_Optional_Config.setAcceptDrops(False)
        self.plainText_Specifier_Optional_Config.setAutoFillBackground(True)
        self.plainText_Specifier_Optional_Config.setReadOnly(False)
        self.label_Specifier_2_Optional_Config = QLabel(self.Config)
        self.label_Specifier_2_Optional_Config.setObjectName(u"label_Specifier_2_Optional_Config")
        self.label_Specifier_2_Optional_Config.setGeometry(QRect(490, 230, 151, 21))
        self.label_Specifier_2_Optional_Config.setFont(font1)
        self.toolButton_Modify_Config = QToolButton(self.Config)
        self.toolButton_Modify_Config.setObjectName(u"toolButton_Modify_Config")
        self.toolButton_Modify_Config.setGeometry(QRect(460, 10, 61, 31))
        self.toolButton_Modify_Config.setAutoFillBackground(True)
        self.toolButton_Delete_Config = QToolButton(self.Config)
        self.toolButton_Delete_Config.setObjectName(u"toolButton_Delete_Config")
        self.toolButton_Delete_Config.setGeometry(QRect(380, 10, 61, 31))
        self.toolButton_Delete_Config.setAutoFillBackground(True)
        self.toolButton_Add_New_Config__Accept_Config = QToolButton(self.Config)
        self.toolButton_Add_New_Config__Accept_Config.setObjectName(u"toolButton_Add_New_Config__Accept_Config")
        self.toolButton_Add_New_Config__Accept_Config.setGeometry(QRect(530, 10, 121, 31))
        self.toolButton_Add_New_Config__Accept_Config.setAutoFillBackground(True)
        self.tabWidget.addTab(self.Config, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.SelectionButton_Tree.setDefault(True)
        self.loadBatton_Tree.setDefault(True)
        self.SelectionButton_Auto.setDefault(True)
        self.loadBatton_Auto.setDefault(True)
        self.SelectionButton_Manual.setDefault(True)
        self.loadBatton_Manual.setDefault(True)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.path_Tree.setPlainText(QCoreApplication.translate("MainWindow", u".../CCSEM3-RA-02_Esp32_WEV_BLE_19082025.bin", None))
        self.SelectionButton_Tree.setText(QCoreApplication.translate("MainWindow", u"\U0001f4c2 Selection", None))
        self.loadBatton_Tree.setText(QCoreApplication.translate("MainWindow", u"\u2b06\ufe0f Load", None))
        self.resetButton_Tree.setText(QCoreApplication.translate("MainWindow", u"\U0001f501", None))
        self.label_Reset_Tree.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.plainTextIP_Tree.setPlainText("")
        self.label_IP_Tree.setText(QCoreApplication.translate("MainWindow", u"IP", None))
        self.label_ID_Auto_2.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.plainText_Port_Tree.setPlainText("")
        self.plainText_ID_Tree.setPlainText("")
        self.label_Port_Auto_2.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.comboBox_Level_1_Name_Tree.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_Level_1_Name_Tree.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_Level_1_Name_Tree.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_Level_1_Name_Tree.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_Level_1_Name_Tree.setItemText(4, QCoreApplication.translate("MainWindow", u"5", None))

        self.comboBox_Level_1_ID_Tree.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.comboBox_Level_1_ID_Tree.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_Level_1_ID_Tree.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_Level_1_ID_Tree.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_Level_1_ID_Tree.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_Level_1_ID_Tree.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_Level_1_ID_Tree.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_Level_1_ID_Tree.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_Level_1_ID_Tree.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_Level_1_ID_Tree.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_Level_1_ID_Tree.setItemText(10, QCoreApplication.translate("MainWindow", u"A", None))
        self.comboBox_Level_1_ID_Tree.setItemText(11, QCoreApplication.translate("MainWindow", u"B", None))
        self.comboBox_Level_1_ID_Tree.setItemText(12, QCoreApplication.translate("MainWindow", u"C", None))
        self.comboBox_Level_1_ID_Tree.setItemText(13, QCoreApplication.translate("MainWindow", u"D", None))
        self.comboBox_Level_1_ID_Tree.setItemText(14, QCoreApplication.translate("MainWindow", u"F", None))

        self.comboBox_Level_2_Name_Tree.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_Level_2_Name_Tree.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_Level_2_Name_Tree.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_Level_2_Name_Tree.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_Level_2_Name_Tree.setItemText(4, QCoreApplication.translate("MainWindow", u"5", None))

        self.comboBox_Level_3_Name_Tree.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_Level_3_Name_Tree.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_Level_3_Name_Tree.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_Level_3_Name_Tree.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_Level_3_Name_Tree.setItemText(4, QCoreApplication.translate("MainWindow", u"5", None))

        self.label_pointer_Tree_1.setText(QCoreApplication.translate("MainWindow", u"\u2192", None))
        self.label_pointer_Tree_2.setText(QCoreApplication.translate("MainWindow", u"\u2192", None))
        self.label_pointer_Tree_3.setText(QCoreApplication.translate("MainWindow", u"\u2192", None))
        self.label_pointer_Tree_4.setText(QCoreApplication.translate("MainWindow", u"\u2192", None))
        self.label_pointer_Tree_5.setText(QCoreApplication.translate("MainWindow", u"\u2192", None))
        self.comboBox_Level_2_ID_Tree.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.comboBox_Level_2_ID_Tree.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_Level_2_ID_Tree.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_Level_2_ID_Tree.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_Level_2_ID_Tree.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_Level_2_ID_Tree.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_Level_2_ID_Tree.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_Level_2_ID_Tree.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_Level_2_ID_Tree.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_Level_2_ID_Tree.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_Level_2_ID_Tree.setItemText(10, QCoreApplication.translate("MainWindow", u"A", None))
        self.comboBox_Level_2_ID_Tree.setItemText(11, QCoreApplication.translate("MainWindow", u"B", None))
        self.comboBox_Level_2_ID_Tree.setItemText(12, QCoreApplication.translate("MainWindow", u"C", None))
        self.comboBox_Level_2_ID_Tree.setItemText(13, QCoreApplication.translate("MainWindow", u"D", None))
        self.comboBox_Level_2_ID_Tree.setItemText(14, QCoreApplication.translate("MainWindow", u"F", None))

        self.comboBox_Level_3_ID_Tree.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.comboBox_Level_3_ID_Tree.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_Level_3_ID_Tree.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_Level_3_ID_Tree.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_Level_3_ID_Tree.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_Level_3_ID_Tree.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_Level_3_ID_Tree.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_Level_3_ID_Tree.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_Level_3_ID_Tree.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_Level_3_ID_Tree.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_Level_3_ID_Tree.setItemText(10, QCoreApplication.translate("MainWindow", u"A", None))
        self.comboBox_Level_3_ID_Tree.setItemText(11, QCoreApplication.translate("MainWindow", u"B", None))
        self.comboBox_Level_3_ID_Tree.setItemText(12, QCoreApplication.translate("MainWindow", u"C", None))
        self.comboBox_Level_3_ID_Tree.setItemText(13, QCoreApplication.translate("MainWindow", u"D", None))
        self.comboBox_Level_3_ID_Tree.setItemText(14, QCoreApplication.translate("MainWindow", u"F", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TreeMode), QCoreApplication.translate("MainWindow", u"Tree mode", None))
        self.SelectionButton_Auto.setText(QCoreApplication.translate("MainWindow", u"\U0001f4c2 Selection", None))
        self.loadBatton_Auto.setText(QCoreApplication.translate("MainWindow", u"\u2b06\ufe0f Load", None))
        self.plainText_Name_Auto.setPlainText("")
        self.plainText_Type_Auto.setPlainText("")
        self.plainText_ID_Auto.setPlainText("")
        self.plainText_Port_Auto.setPlainText("")
        self.plainText_IP_Auto.setPlainText("")
        self.path_Auto.setPlainText(QCoreApplication.translate("MainWindow", u".../CCSEM3-RA-02_Esp32_WEV_BLE_19082025.bin", None))
        self.label_Name_Auto.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_Specifier_Auto.setText(QCoreApplication.translate("MainWindow", u"Specifier", None))
        self.label_ID_Auto.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.label_Port_Auto.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.label_IP_Auto.setText(QCoreApplication.translate("MainWindow", u"IP", None))
        self.resetButton_Auto.setText(QCoreApplication.translate("MainWindow", u"\U0001f501", None))
        self.label_Reset_Auto.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AutoMode), QCoreApplication.translate("MainWindow", u"Auto Mode", None))
        self.SelectionButton_Manual.setText(QCoreApplication.translate("MainWindow", u"\U0001f4c2 Selection", None))
        self.loadBatton_Manual.setText(QCoreApplication.translate("MainWindow", u"\u2b06\ufe0f Load", None))
        self.path_Manual.setPlainText(QCoreApplication.translate("MainWindow", u".../CCSEM3-RA-02_Esp32_WEV_BLE_19082025.bin", None))
        self.plainTextPort_Manual.setPlainText("")
        self.plainTextIP_Manual.setPlainText("")
        self.plainTextID_Manual.setPlainText("")
        self.label_ID_Manual.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.label_Port_Manual.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.label_IP_Manual.setText(QCoreApplication.translate("MainWindow", u"IP", None))
        self.checkBox_Yes_IP.setText(QCoreApplication.translate("MainWindow", u"YES", None))
        self.checkBox_NO_IP.setText(QCoreApplication.translate("MainWindow", u"NO", None))
        self.checkBox_Safety_Mode_Manual.setText(QCoreApplication.translate("MainWindow", u"Safety mode \U0001f6e1\U0000fe0f", None))
        self.resetButton_Manual.setText(QCoreApplication.translate("MainWindow", u"\U0001f501", None))
        self.label_Reset_Manual.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ManualMode), QCoreApplication.translate("MainWindow", u"Manual Mode", None))
        self.plainText_Port_Config.setPlainText("")
        self.label_Name_Config.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.plainText_IP_Config.setPlainText("")
        self.plainText_Specifier_Config.setPlainText("")
        self.label_Specifier_Config.setText(QCoreApplication.translate("MainWindow", u"Specifier", None))
        self.plainText_ID_Config.setPlainText("")
        self.plainText_Name_Config.setPlainText("")
        self.label_ID_Config.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.label_Port_Config.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.checkBox_NO_IP_2.setText(QCoreApplication.translate("MainWindow", u"NO", None))
        self.label_IP_Config.setText(QCoreApplication.translate("MainWindow", u"IP", None))
        self.checkBox_Yes_IP_2.setText(QCoreApplication.translate("MainWindow", u"YES", None))
        self.plainText_Specifier_Optional_Config.setPlainText("")
        self.label_Specifier_2_Optional_Config.setText(QCoreApplication.translate("MainWindow", u"Specifier 2 (optional)", None))
        self.toolButton_Modify_Config.setText(QCoreApplication.translate("MainWindow", u"\u270f\ufe0fModify", None))
        self.toolButton_Delete_Config.setText(QCoreApplication.translate("MainWindow", u"\U0001f5d1\U0000fe0fDelete", None))
        self.toolButton_Add_New_Config__Accept_Config.setText(QCoreApplication.translate("MainWindow", u"\U0001f4ddAdd New/Accept", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Config), QCoreApplication.translate("MainWindow", u"Config", None))
    # retranslateUi

