# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'v1.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QHeaderView,
    QLabel, QListView, QMainWindow, QPlainTextEdit,
    QProgressBar, QPushButton, QSizePolicy, QTabWidget,
    QTableView, QToolButton, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(661, 400)
        MainWindow.setMinimumSize(QSize(661, 400))
        MainWindow.setMaximumSize(QSize(661, 400))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(660, 400))
        self.centralwidget.setMaximumSize(QSize(660, 400))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 661, 401))
        self.tabWidget.setMinimumSize(QSize(661, 401))
        self.tabWidget.setMaximumSize(QSize(661, 440))
        self.tabWidget.setElideMode(Qt.TextElideMode.ElideMiddle)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.AutoMode = QWidget()
        self.AutoMode.setObjectName(u"AutoMode")
        self.SelectionButton_auto = QPushButton(self.AutoMode)
        self.SelectionButton_auto.setObjectName(u"SelectionButton_auto")
        self.SelectionButton_auto.setGeometry(QRect(480, 80, 161, 31))
        self.SelectionButton_auto.setAutoDefault(False)
        self.SelectionButton_auto.setFlat(True)
        self.loadBatton_auto = QPushButton(self.AutoMode)
        self.loadBatton_auto.setObjectName(u"loadBatton_auto")
        self.loadBatton_auto.setGeometry(QRect(10, 80, 141, 31))
        self.loadBatton_auto.setFlat(True)
        self.plainTextName_Auto = QPlainTextEdit(self.AutoMode)
        self.plainTextName_Auto.setObjectName(u"plainTextName_Auto")
        self.plainTextName_Auto.setGeometry(QRect(490, 150, 161, 31))
        self.plainTextName_Auto.setAcceptDrops(False)
        self.plainTextName_Auto.setAutoFillBackground(True)
        self.plainTextName_Auto.setReadOnly(True)
        self.plainTextType_Auto = QPlainTextEdit(self.AutoMode)
        self.plainTextType_Auto.setObjectName(u"plainTextType_Auto")
        self.plainTextType_Auto.setGeometry(QRect(490, 190, 161, 31))
        self.plainTextType_Auto.setAutoFillBackground(True)
        self.plainTextType_Auto.setReadOnly(True)
        self.plainTextID_Auto = QPlainTextEdit(self.AutoMode)
        self.plainTextID_Auto.setObjectName(u"plainTextID_Auto")
        self.plainTextID_Auto.setGeometry(QRect(490, 230, 161, 31))
        self.plainTextID_Auto.setAutoFillBackground(True)
        self.plainTextID_Auto.setReadOnly(True)
        self.plainTextPort_Auto = QPlainTextEdit(self.AutoMode)
        self.plainTextPort_Auto.setObjectName(u"plainTextPort_Auto")
        self.plainTextPort_Auto.setGeometry(QRect(490, 270, 161, 31))
        self.plainTextPort_Auto.setAutoFillBackground(True)
        self.plainTextPort_Auto.setReadOnly(True)
        self.plainTextIP_Auto = QPlainTextEdit(self.AutoMode)
        self.plainTextIP_Auto.setObjectName(u"plainTextIP_Auto")
        self.plainTextIP_Auto.setGeometry(QRect(490, 310, 161, 31))
        self.plainTextIP_Auto.setAutoFillBackground(True)
        self.plainTextIP_Auto.setReadOnly(True)
        self.path_auto = QPlainTextEdit(self.AutoMode)
        self.path_auto.setObjectName(u"path_auto")
        self.path_auto.setGeometry(QRect(10, 3, 641, 61))
        font = QFont()
        font.setPointSize(20)
        self.path_auto.setFont(font)
        self.progressBar = QProgressBar(self.AutoMode)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(170, 80, 311, 31))
        self.progressBar.setValue(24)
        self.label_4 = QLabel(self.AutoMode)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(440, 160, 49, 16))
        font1 = QFont()
        font1.setPointSize(12)
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.AutoMode)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(430, 200, 61, 16))
        self.label_5.setFont(font1)
        self.label_6 = QLabel(self.AutoMode)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(440, 240, 49, 16))
        self.label_6.setFont(font1)
        self.label_7 = QLabel(self.AutoMode)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(440, 280, 49, 16))
        self.label_7.setFont(font1)
        self.label_8 = QLabel(self.AutoMode)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(440, 320, 49, 16))
        self.label_8.setFont(font1)
        self.StagesListView_manual_2 = QListView(self.AutoMode)
        self.StagesListView_manual_2.setObjectName(u"StagesListView_manual_2")
        self.StagesListView_manual_2.setGeometry(QRect(10, 120, 411, 241))
        self.StagesListView_manual_2.setAutoFillBackground(True)
        self.tabWidget.addTab(self.AutoMode, "")
        self.ManualMode = QWidget()
        self.ManualMode.setObjectName(u"ManualMode")
        self.SelectionButton_manual = QPushButton(self.ManualMode)
        self.SelectionButton_manual.setObjectName(u"SelectionButton_manual")
        self.SelectionButton_manual.setGeometry(QRect(480, 80, 161, 31))
        self.SelectionButton_manual.setAutoDefault(False)
        self.SelectionButton_manual.setFlat(True)
        self.loadBatton_manual = QPushButton(self.ManualMode)
        self.loadBatton_manual.setObjectName(u"loadBatton_manual")
        self.loadBatton_manual.setGeometry(QRect(10, 80, 141, 31))
        self.loadBatton_manual.setFlat(True)
        self.path_manual = QPlainTextEdit(self.ManualMode)
        self.path_manual.setObjectName(u"path_manual")
        self.path_manual.setGeometry(QRect(10, 3, 641, 61))
        self.path_manual.setFont(font)
        self.progressBar_manual = QProgressBar(self.ManualMode)
        self.progressBar_manual.setObjectName(u"progressBar_manual")
        self.progressBar_manual.setGeometry(QRect(170, 80, 311, 31))
        self.progressBar_manual.setValue(24)
        self.plainTextPort_Manual = QPlainTextEdit(self.ManualMode)
        self.plainTextPort_Manual.setObjectName(u"plainTextPort_Manual")
        self.plainTextPort_Manual.setGeometry(QRect(480, 200, 161, 31))
        self.plainTextPort_Manual.setAutoFillBackground(True)
        self.plainTextPort_Manual.setReadOnly(False)
        self.plainTextIP_Manual = QPlainTextEdit(self.ManualMode)
        self.plainTextIP_Manual.setObjectName(u"plainTextIP_Manual")
        self.plainTextIP_Manual.setGeometry(QRect(480, 290, 161, 31))
        self.plainTextIP_Manual.setAutoFillBackground(True)
        self.plainTextIP_Manual.setReadOnly(False)
        self.plainTextID_Manual = QPlainTextEdit(self.ManualMode)
        self.plainTextID_Manual.setObjectName(u"plainTextID_Manual")
        self.plainTextID_Manual.setGeometry(QRect(480, 140, 161, 31))
        self.plainTextID_Manual.setAutoFillBackground(True)
        self.plainTextID_Manual.setReadOnly(False)
        self.label = QLabel(self.ManualMode)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(450, 150, 49, 16))
        self.label.setFont(font1)
        self.label_2 = QLabel(self.ManualMode)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(440, 210, 49, 16))
        self.label_2.setFont(font1)
        self.label_3 = QLabel(self.ManualMode)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(550, 240, 16, 16))
        self.label_3.setFont(font1)
        self.checkBox_Yes_IP = QCheckBox(self.ManualMode)
        self.checkBox_Yes_IP.setObjectName(u"checkBox_Yes_IP")
        self.checkBox_Yes_IP.setGeometry(QRect(480, 260, 51, 24))
        self.checkBox_Yes_IP.setAutoFillBackground(False)
        self.checkBox_NO_IP = QCheckBox(self.ManualMode)
        self.checkBox_NO_IP.setObjectName(u"checkBox_NO_IP")
        self.checkBox_NO_IP.setGeometry(QRect(590, 260, 51, 24))
        self.checkBox_NO_IP.setAutoFillBackground(False)
        self.checkBox_Safety_mode = QCheckBox(self.ManualMode)
        self.checkBox_Safety_mode.setObjectName(u"checkBox_Safety_mode")
        self.checkBox_Safety_mode.setGeometry(QRect(480, 330, 161, 21))
        self.checkBox_Safety_mode.setFont(font1)
        self.checkBox_Safety_mode.setAutoFillBackground(False)
        self.checkBox_Safety_mode.setChecked(True)
        self.checkBox_Safety_mode.setAutoRepeat(False)
        self.checkBox_Safety_mode.setAutoExclusive(False)
        self.checkBox_Safety_mode.setTristate(False)
        self.StagesListView_manual_3 = QListView(self.ManualMode)
        self.StagesListView_manual_3.setObjectName(u"StagesListView_manual_3")
        self.StagesListView_manual_3.setGeometry(QRect(10, 120, 411, 241))
        self.StagesListView_manual_3.setAutoFillBackground(True)
        self.tabWidget.addTab(self.ManualMode, "")
        self.Config = QWidget()
        self.Config.setObjectName(u"Config")
        self.tableView = QTableView(self.Config)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setGeometry(QRect(10, 10, 361, 351))
        self.tableView.setAutoFillBackground(True)
        self.tableView.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.tableView.setFrameShadow(QFrame.Shadow.Sunken)
        self.tableView.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.plainTextPort_Config = QPlainTextEdit(self.Config)
        self.plainTextPort_Config.setObjectName(u"plainTextPort_Config")
        self.plainTextPort_Config.setGeometry(QRect(480, 190, 161, 31))
        self.plainTextPort_Config.setAutoFillBackground(True)
        self.plainTextPort_Config.setReadOnly(True)
        self.label_9 = QLabel(self.Config)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(430, 80, 49, 16))
        self.label_9.setFont(font1)
        self.plainTextIP_Config = QPlainTextEdit(self.Config)
        self.plainTextIP_Config.setObjectName(u"plainTextIP_Config")
        self.plainTextIP_Config.setGeometry(QRect(480, 330, 161, 31))
        self.plainTextIP_Config.setAutoFillBackground(True)
        self.plainTextIP_Config.setReadOnly(True)
        self.plainTextSpecifier_Config = QPlainTextEdit(self.Config)
        self.plainTextSpecifier_Config.setObjectName(u"plainTextSpecifier_Config")
        self.plainTextSpecifier_Config.setGeometry(QRect(480, 110, 161, 31))
        self.plainTextSpecifier_Config.setAutoFillBackground(True)
        self.plainTextSpecifier_Config.setReadOnly(True)
        self.label_11 = QLabel(self.Config)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(420, 110, 61, 31))
        self.label_11.setFont(font1)
        self.plainTextID_Config = QPlainTextEdit(self.Config)
        self.plainTextID_Config.setObjectName(u"plainTextID_Config")
        self.plainTextID_Config.setGeometry(QRect(480, 150, 161, 31))
        self.plainTextID_Config.setAutoFillBackground(True)
        self.plainTextID_Config.setReadOnly(True)
        self.plainTextName_Config = QPlainTextEdit(self.Config)
        self.plainTextName_Config.setObjectName(u"plainTextName_Config")
        self.plainTextName_Config.setGeometry(QRect(480, 70, 161, 31))
        self.plainTextName_Config.setAcceptDrops(False)
        self.plainTextName_Config.setAutoFillBackground(True)
        self.plainTextName_Config.setReadOnly(True)
        self.label_12 = QLabel(self.Config)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(430, 160, 49, 16))
        self.label_12.setFont(font1)
        self.label_13 = QLabel(self.Config)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(430, 200, 49, 16))
        self.label_13.setFont(font1)
        self.checkBox_NO_IP_2 = QCheckBox(self.Config)
        self.checkBox_NO_IP_2.setObjectName(u"checkBox_NO_IP_2")
        self.checkBox_NO_IP_2.setGeometry(QRect(580, 300, 51, 24))
        self.checkBox_NO_IP_2.setAutoFillBackground(False)
        self.label_10 = QLabel(self.Config)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(550, 290, 16, 16))
        self.label_10.setFont(font1)
        self.checkBox_Yes_IP_2 = QCheckBox(self.Config)
        self.checkBox_Yes_IP_2.setObjectName(u"checkBox_Yes_IP_2")
        self.checkBox_Yes_IP_2.setGeometry(QRect(480, 300, 51, 24))
        self.checkBox_Yes_IP_2.setAutoFillBackground(False)
        self.plainTextSpecifierOptional_Config = QPlainTextEdit(self.Config)
        self.plainTextSpecifierOptional_Config.setObjectName(u"plainTextSpecifierOptional_Config")
        self.plainTextSpecifierOptional_Config.setGeometry(QRect(480, 250, 161, 31))
        self.plainTextSpecifierOptional_Config.setAcceptDrops(False)
        self.plainTextSpecifierOptional_Config.setAutoFillBackground(True)
        self.plainTextSpecifierOptional_Config.setReadOnly(True)
        self.label_14 = QLabel(self.Config)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(490, 230, 151, 21))
        self.label_14.setFont(font1)
        self.toolButton_Modify_Config = QToolButton(self.Config)
        self.toolButton_Modify_Config.setObjectName(u"toolButton_Modify_Config")
        self.toolButton_Modify_Config.setGeometry(QRect(460, 10, 61, 31))
        self.toolButton_Modify_Config.setAutoFillBackground(True)
        self.toolButton_Delete_Config = QToolButton(self.Config)
        self.toolButton_Delete_Config.setObjectName(u"toolButton_Delete_Config")
        self.toolButton_Delete_Config.setGeometry(QRect(380, 10, 61, 31))
        self.toolButton_Delete_Config.setAutoFillBackground(True)
        self.toolButton_add_new_config = QToolButton(self.Config)
        self.toolButton_add_new_config.setObjectName(u"toolButton_add_new_config")
        self.toolButton_add_new_config.setGeometry(QRect(530, 10, 121, 31))
        self.toolButton_add_new_config.setAutoFillBackground(True)
        self.tabWidget.addTab(self.Config, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.SelectionButton_auto.setDefault(True)
        self.loadBatton_auto.setDefault(True)
        self.SelectionButton_manual.setDefault(True)
        self.loadBatton_manual.setDefault(True)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.SelectionButton_auto.setText(QCoreApplication.translate("MainWindow", u"\U0001f4c2 \U00000412\U0000044b\U00000431\U0000043e\U00000440", None))
        self.loadBatton_auto.setText(QCoreApplication.translate("MainWindow", u"\u2b06\ufe0f \u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c", None))
        self.plainTextName_Auto.setPlainText("")
        self.plainTextType_Auto.setPlainText("")
        self.plainTextID_Auto.setPlainText("")
        self.plainTextPort_Auto.setPlainText("")
        self.plainTextIP_Auto.setPlainText("")
        self.path_auto.setPlainText(QCoreApplication.translate("MainWindow", u".../CCSEM3-RA-02_Esp32_WEV_BLE_19082025.bin", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Specifier", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"IP", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AutoMode), QCoreApplication.translate("MainWindow", u"Auto Mode", None))
        self.SelectionButton_manual.setText(QCoreApplication.translate("MainWindow", u"\U0001f4c2 \U00000412\U0000044b\U00000431\U0000043e\U00000440", None))
        self.loadBatton_manual.setText(QCoreApplication.translate("MainWindow", u"\u2b06\ufe0f \u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c", None))
        self.path_manual.setPlainText(QCoreApplication.translate("MainWindow", u".../CCSEM3-RA-02_Esp32_WEV_BLE_19082025.bin", None))
        self.plainTextPort_Manual.setPlainText("")
        self.plainTextIP_Manual.setPlainText("")
        self.plainTextID_Manual.setPlainText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"IP", None))
        self.checkBox_Yes_IP.setText(QCoreApplication.translate("MainWindow", u"YES", None))
        self.checkBox_NO_IP.setText(QCoreApplication.translate("MainWindow", u"NO", None))
        self.checkBox_Safety_mode.setText(QCoreApplication.translate("MainWindow", u"Safety mode \U0001f6e1\U0000fe0f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ManualMode), QCoreApplication.translate("MainWindow", u"Manual Mode", None))
        self.plainTextPort_Config.setPlainText("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.plainTextIP_Config.setPlainText("")
        self.plainTextSpecifier_Config.setPlainText("")
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Specifier", None))
        self.plainTextID_Config.setPlainText("")
        self.plainTextName_Config.setPlainText("")
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.checkBox_NO_IP_2.setText(QCoreApplication.translate("MainWindow", u"NO", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"IP", None))
        self.checkBox_Yes_IP_2.setText(QCoreApplication.translate("MainWindow", u"YES", None))
        self.plainTextSpecifierOptional_Config.setPlainText("")
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Specifier 2 (optional)", None))
        self.toolButton_Modify_Config.setText(QCoreApplication.translate("MainWindow", u"\u270f\ufe0fModify", None))
        self.toolButton_Delete_Config.setText(QCoreApplication.translate("MainWindow", u"\U0001f5d1\U0000fe0fDelete", None))
        self.toolButton_add_new_config.setText(QCoreApplication.translate("MainWindow", u"\U0001f4ddAdd New/Accept", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Config), QCoreApplication.translate("MainWindow", u"Config", None))
    # retranslateUi

